clc;
clear;
close all;

disp("Loading Dataset...")

imds = imageDatastore( ...
    "Diabetic_Retinopathy_Dataset", ...
    "IncludeSubfolders", true, ...
    "LabelSource", "foldernames");

[imdsTrain,imdsVal,imdsTest] = splitEachLabel( ...
    imds,...
    0.7,...
    0.15,...
    0.15,...
    "randomized");

disp("Loading ResNet18...")

net = resnet18;

inputSize = net.Layers(1).InputSize;

augTrain = augmentedImageDatastore( ...
    inputSize(1:2), ...
    imdsTrain);

augVal = augmentedImageDatastore( ...
    inputSize(1:2), ...
    imdsVal);

lgraph = layerGraph(net);

numClasses = numel(categories(imds.Labels));

newLayers = [
    fullyConnectedLayer(numClasses,...
    'Name','fc_DR',...
    'WeightLearnRateFactor',10,...
    'BiasLearnRateFactor',10)

    softmaxLayer('Name','softmax_DR')

    classificationLayer('Name','classoutput_DR')
];

lgraph = replaceLayer(lgraph,'fc1000',newLayers(1));
lgraph = replaceLayer(lgraph,'prob',newLayers(2));
lgraph = replaceLayer(lgraph,'ClassificationLayer_predictions',newLayers(3));

options = trainingOptions('adam',...
    'MiniBatchSize',8,...
    'MaxEpochs',10,...
    'InitialLearnRate',1e-4,...
    'ValidationData',augVal,...
    'Verbose',true,...
    'Plots','training-progress');

disp("Starting Training...")

trainedNet = trainNetwork( ...
    augTrain,...
    lgraph,...
    options);

save('DR_Model_ResNet18.mat','trainedNet')

disp("Training Finished!")